### ISSUE TITLE
Missing arguments

### ISSUE THREAD

**Issue by niranjchandrasekaran** [cytomining/pycytominer#147]
@gwaygenomics I could be wrong or I am missing something obvious but it looks like `aggregate_args` is not being passed to `aggregate_compartment` when the function is called within `aggregate_profiles`. 

https://github.com/cytomining/pycytominer/blob/4f37e019918256111933aed4e3b9afb50055b4a1/pycytominer/cyto_utils/cells.py#L621-L671

I am currently using `aggregate_args` to set `operation` to `mean` or `median` for `aggregate` in the profiling recipe but I found that `aggregate` always uses the default `operation`.

**Comment by gwaygenomics** [comment]
Ahh, I see what's going on!

- `aggregate_profiles()` doesn't pass aggregate_args to `aggregate_compartment()`
- This means that there is no way to control aggregation parameters through `aggregate_profiles()`
- Instead, `aggregate_profiles()` will aggregate using the operation defined when you instantiate the `SingleCells()` class since `aggregate_compartment()` uses `operation=self.aggregation_operation`. 
- So, in order to switch between mean and median, at least with the current framework, you would need to instantiate twice with (1) `agg_mean_sc = SingleCells(aggregation_operation="mean")` and (2) `agg_median_sc = SingleCells(aggregation_operation="median")` 

So, we can fix this in one of two ways:

1. Remove the `aggregate_args` variable from `aggregate_profiles()` to avoid confusion.
2. Enable a user to modify aggregation parameters at common entry points that override how the class was instantiated

Niranj, you are in the best position to determine if we should pursue 2. I can see an argument for both yes and no! One the one hand, flexibility is often helpful, but on the other hand, it might be confusing to have a scenario where `SingleCells()` is instantiated with one aggregate_operation but then profiles are generated with the initial operation ignored. The question to ask is: "which option would make it better for users"?

**Comment by niranjchandrasekaran** [comment]
> Instead, aggregate_profiles() will aggregate using the operation defined when you instantiate the SingleCells() class since aggregate_compartment() uses operation=self.aggregation_operation.

Ahh, makes sense. I was staring at the code for while without realizing this was the case.

> Niranj, you are in the best position to determine if we should pursue 2. I can see an argument for both yes and no! One the one hand, flexibility is often helpful, but on the other hand, it might be confusing to have a scenario where SingleCells() is instantiated with one aggregate_operation but then profiles are generated with the initial operation ignored. The question to ask is: "which option would make it better for users"?

I am in favor of option 1 given how confused I was yesterday :)

**Comment by gwaygenomics** [comment]
Sounds good - this does beg the question then, however, why use `aggregate_args` at all?

**Comment by niranjchandrasekaran** [comment]
At the moment, we are using it to pass `features` and `object_feature` to `aggregate()`, both of these are defined within `aggregate_compartments()`

https://github.com/cytomining/pycytominer/blob/4f37e019918256111933aed4e3b9afb50055b4a1/pycytominer/cyto_utils/cells.py#L439-L451

We could remove `aggregate_args` altogether and add `features` and `object_feature` as parameters to `aggregate()`

https://github.com/cytomining/pycytominer/blob/4f37e019918256111933aed4e3b9afb50055b4a1/pycytominer/cyto_utils/cells.py#L453-L460

**Comment by gwaygenomics** [comment]
> We could remove aggregate_args altogether and add features and object_feature as parameters to aggregate()

Yep, and define them in `__init__()` with reasonable defaults. I very well could be failing to think of important edge cases, think this might simplify things...

**Comment by niranjchandrasekaran** [comment]
Sounds good. I will make these changes and have a PR for you next week.
